import SwiftUI

struct TermsOfServiceView: View {
    private let lastUpdated = "March 11, 2026"

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                // Header
                VStack(alignment: .leading, spacing: 8) {
                    Text("Last updated: \(lastUpdated)")
                        .font(.system(size: 13))
                        .foregroundStyle(.secondary)

                    Text("By using Today+, you agree to the following terms. Please read them carefully.")
                        .font(.system(size: 15))
                        .foregroundStyle(.secondary)
                        .lineSpacing(3)
                }

                section(
                    number: "1",
                    title: "Acceptance of Terms",
                    content: """
                    By downloading, installing, or using the Today+ application ("App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.

                    These Terms constitute a legally binding agreement between you and Today+ ("we", "us", "our").
                    """
                )

                section(
                    number: "2",
                    title: "Description of Service",
                    content: """
                    Today+ is a personalized news aggregation application that uses artificial intelligence to curate and deliver news content from various sources. The App provides:

                    • AI-powered personalized news feeds
                    • Breaking news notifications
                    • Article bookmarking and reading history
                    • Content personalization based on your preferences

                    We reserve the right to modify, suspend, or discontinue any aspect of the service at any time.
                    """
                )

                section(
                    number: "3",
                    title: "User Accounts",
                    content: """
                    You may use Today+ as a guest or create an account. When creating an account:

                    • You must provide accurate and complete information
                    • You are responsible for maintaining the security of your account
                    • You must notify us immediately of any unauthorized use
                    • You must be at least 13 years old to create an account

                    We reserve the right to suspend or terminate accounts that violate these Terms.
                    """
                )

                section(
                    number: "4",
                    title: "Content & Intellectual Property",
                    content: """
                    **News Content**: Articles displayed in Today+ are sourced from third-party publishers. We do not claim ownership of this content. Each article is attributed to its original source.

                    **AI Summaries**: Summaries and bullet points generated by our AI are derivative works created for informational purposes. They should not be considered as original reporting.

                    **App Content**: The Today+ app design, code, branding, and original content are owned by us and protected by intellectual property laws.

                    You may not reproduce, distribute, or create derivative works from our App without permission.
                    """
                )

                section(
                    number: "5",
                    title: "Acceptable Use",
                    content: """
                    You agree not to:

                    • Use the App for any unlawful purpose
                    • Attempt to gain unauthorized access to our systems
                    • Scrape, crawl, or automatically collect content from the App
                    • Interfere with or disrupt the App's functionality
                    • Impersonate any person or entity
                    • Use the App to spread misinformation or harmful content
                    • Reverse engineer, decompile, or disassemble the App
                    """
                )

                section(
                    number: "6",
                    title: "Disclaimer of Warranties",
                    content: """
                    The App is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to:

                    • Accuracy or completeness of news content
                    • Uninterrupted or error-free service
                    • Fitness for a particular purpose
                    • Non-infringement of third-party rights

                    We do not guarantee the accuracy of AI-generated summaries. Always refer to the original source for authoritative reporting.
                    """
                )

                section(
                    number: "7",
                    title: "Limitation of Liability",
                    content: """
                    To the maximum extent permitted by law, Today+ shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from:

                    • Your use or inability to use the App
                    • Any content obtained from the App
                    • Unauthorized access to your data
                    • Any interruption or cessation of service

                    Our total liability shall not exceed the amount you paid for the App in the twelve months preceding the claim.
                    """
                )

                section(
                    number: "8",
                    title: "Notifications & Communications",
                    content: """
                    By enabling notifications, you consent to receive:

                    • Breaking news alerts
                    • Feed update notifications
                    • Important service announcements

                    You can manage notification preferences in your profile settings at any time.
                    """
                )

                section(
                    number: "9",
                    title: "Termination",
                    content: """
                    You may stop using the App at any time. You can delete your account through the profile settings.

                    We may terminate or suspend your access if you violate these Terms. Upon termination, your right to use the App ceases immediately, though certain provisions of these Terms will survive.
                    """
                )

                section(
                    number: "10",
                    title: "Governing Law",
                    content: """
                    These Terms are governed by and construed in accordance with applicable laws. Any disputes arising from these Terms will be resolved through binding arbitration, except where prohibited by law.
                    """
                )

                section(
                    number: "11",
                    title: "Changes to Terms",
                    content: """
                    We reserve the right to update these Terms at any time. Material changes will be communicated through the App or via email. Your continued use of Today+ after changes take effect constitutes acceptance of the revised Terms.
                    """
                )

                section(
                    number: "12",
                    title: "Contact",
                    content: """
                    For questions about these Terms, please contact us:

                    **Email**: info@todayplus.news
                    **Website**: todayplus.news
                    """
                )

                Spacer().frame(height: 40)
            }
            .padding(.horizontal, 20)
            .padding(.top, 16)
        }
        .background(Theme.Colors.backgroundPrimary)
        .navigationTitle("Terms of Service")
        .navigationBarTitleDisplayMode(.large)
    }

    private func section(number: String, title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("\(number). \(title)")
                .font(.system(size: 18, weight: .bold))

            Text(LocalizedStringKey(content))
                .font(.system(size: 15))
                .foregroundStyle(.secondary)
                .lineSpacing(4)
        }
    }
}

#Preview {
    NavigationStack {
        TermsOfServiceView()
    }
}
