-- Migration to add ai_detailed_text field to articles table
-- Run this SQL in your Supabase SQL Editor or local SQLite database

-- For SQLite (local development)
ALTER TABLE articles ADD COLUMN ai_detailed_text TEXT;

-- For Supabase (PostgreSQL) - if the field doesn't exist
-- ALTER TABLE articles ADD COLUMN IF NOT EXISTS ai_detailed_text TEXT;

-- Update existing records to use summary as detailed_text temporarily
UPDATE articles 
SET ai_detailed_text = summary 
WHERE ai_detailed_text IS NULL AND summary IS NOT NULL;

-- Add index for better performance
CREATE INDEX IF NOT EXISTS idx_articles_detailed_text ON articles(ai_detailed_text);

-- Update the comment to reflect the new field
COMMENT ON COLUMN articles.ai_detailed_text IS 'Detailed article text (150-200 words) generated by AI';
