# Railway/Nixpacks Configuration
# FORCE Python-only detection, NO Node.js

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'No build phase needed for Python scripts'"]

[start]
cmd = "echo 'Cron jobs configured. Services will run on schedule.'"

