# TEN NEWS - CLEANED ELITE RSS FEED LIST
# Total: 293 Premium Elite Sources
# Categories (focused NEWS platform, 2026-06-07 prune): News, Science,
#             Technology, Business, Sports, Crypto, Space, Health
# (Soft/lifestyle categories removed in the pivot back to serious news:
#  food, travel, fashion, gaming, entertainment, music, humor, automotive,
#  consumer, pets, outdoor, home, books, design, nature, history.)
# Countries (15): USA, UK, Canada, Australia, India, Germany, France, Spain,
#                 Italy, Ukraine, Russia, Turkiye, China, Japan, Israel

RSS_FEEDS = [
    {
        'name': 'The New York Times World',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times US',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/US.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times Homepage',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times Technology',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times Science',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times Climate',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times Space',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/Space.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'The New York Times Health',
        'url': 'https://rss.nytimes.com/services/xml/rss/nyt/Health.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Washington Post World',
        'url': 'https://feeds.washingtonpost.com/rss/world',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Washington Post National',
        'url': 'https://feeds.washingtonpost.com/rss/national',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'NPR News',
        'url': 'https://feeds.npr.org/1001/rss.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'NPR World',
        'url': 'https://feeds.npr.org/1004/rss.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'PBS NewsHour Headlines',
        'url': 'https://www.pbs.org/newshour/feeds/rss/headlines',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'PBS NewsHour Politics',
        'url': 'https://www.pbs.org/newshour/feeds/rss/politics',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'BBC News Business',
        'url': 'https://feeds.bbci.co.uk/news/business/rss.xml',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'BBC News Politics',
        'url': 'https://feeds.bbci.co.uk/news/politics/rss.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'BBC News Health',
        'url': 'https://feeds.bbci.co.uk/news/health/rss.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'BBC News Science & Environment',
        'url': 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'BBC News Technology',
        'url': 'https://feeds.bbci.co.uk/news/technology/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Sky News Home',
        'url': 'https://feeds.skynews.com/feeds/rss/home.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Sky News World',
        'url': 'https://feeds.skynews.com/feeds/rss/world.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Telegraph',
        'url': 'https://www.telegraph.co.uk/rss.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Independent',
        'url': 'https://www.independent.co.uk/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Daily Mail News',
        'url': 'https://www.dailymail.co.uk/news/index.rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Daily Mail Home',
        'url': 'https://www.dailymail.co.uk/home/index.rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Deutsche Welle',
        'url': 'https://rss.dw.com/xml/rss-en-all',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'France 24',
        'url': 'https://www.france24.com/en/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'France 24 Europe',
        'url': 'https://www.france24.com/en/europe/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'France 24 Africa',
        'url': 'https://www.france24.com/en/africa/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'France 24 Middle East',
        'url': 'https://www.france24.com/en/middle-east/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'France 24 Americas',
        'url': 'https://www.france24.com/en/americas/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'France 24 Asia Pacific',
        'url': 'https://www.france24.com/en/asia-pacific/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Euronews',
        'url': 'https://www.euronews.com/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Japan Times',
        'url': 'https://www.japantimes.co.jp/feed/',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'South China Morning Post',
        'url': 'https://www.scmp.com/rss/91/feed',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Straits Times',
        'url': 'https://www.straitstimes.com/news/world/rss.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Sydney Morning Herald',
        'url': 'https://www.smh.com.au/rss/feed.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'El País English',
        'url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada',
        'category': 'news',
        'tier': 'premium',
        'country': 'Spain',
    },
    {
        'name': 'The Times of Israel',
        'url': 'https://www.timesofisrael.com/feed/',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'UN News',
        'url': 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'TIME Magazine',
        'url': 'https://time.com/feed/',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Newsweek',
        'url': 'https://www.newsweek.com/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Atlantic',
        'url': 'https://www.theatlantic.com/feed/all/',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The New Yorker',
        'url': 'https://www.newyorker.com/feed/everything',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Vanity Fair',
        'url': 'https://www.vanityfair.com/feed/rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'ProPublica',
        'url': 'https://www.propublica.org/feeds/propublica/main',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'The Intercept',
        'url': 'https://theintercept.com/feed/?rss',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Financial Times',
        'url': 'https://www.ft.com/?format=rss',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'The Wall Street Journal',
        'url': 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Fortune',
        'url': 'https://fortune.com/feed',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Business Insider',
        'url': 'https://www.businessinsider.com/rss',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'CNBC',
        'url': 'https://www.cnbc.com/id/100003114/device/rss/rss.html',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'CNBC Top News',
        'url': 'https://www.cnbc.com/id/100727362/device/rss/rss.html',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Seeking Alpha',
        'url': 'https://seekingalpha.com/feed.xml',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'The Economist Business',
        'url': 'https://www.economist.com/business/rss.xml',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'The Economist Finance',
        'url': 'https://www.economist.com/finance-and-economics/rss.xml',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'VentureBeat',
        'url': 'https://venturebeat.com/feed/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Inc. Magazine',
        'url': 'https://www.inc.com/rss/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Marketing Week',
        'url': 'https://www.marketingweek.com/feed/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Supply Chain Dive',
        'url': 'https://www.supplychaindive.com/feeds/news/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Manufacturing Dive',
        'url': 'https://www.manufacturingdive.com/feeds/news/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Retail Dive',
        'url': 'https://www.retaildive.com/feeds/news/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Oilprice.com',
        'url': 'https://oilprice.com/rss/main',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'South China Morning Post Business',
        'url': 'https://www.scmp.com/rss/2/feed',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Nikkei Asia',
        'url': 'https://asia.nikkei.com/rss/feed/nar',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'China Daily Business',
        'url': 'http://www.chinadaily.com.cn/rss/bizchina_rss.xml',
        'category': 'business',
        'tier': 'premium',
        'country': 'China',
    },
    {
        'name': 'Financial Times Asia',
        'url': 'https://www.ft.com/asia-pacific?format=rss',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'NerdWallet',
        'url': 'https://www.nerdwallet.com/blog/feed/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Kiplinger',
        'url': 'https://www.kiplinger.com/feed/all',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'MarketWatch',
        'url': 'https://www.marketwatch.com/rss/topstories',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Yahoo Finance',
        'url': 'https://finance.yahoo.com/news/rssindex',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Money Magazine',
        'url': 'https://money.com/feed/',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'The Verge',
        'url': 'https://www.theverge.com/rss/index.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Wired',
        'url': 'https://www.wired.com/feed/rss',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'MIT Technology Review',
        'url': 'https://www.technologyreview.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'TechCrunch',
        'url': 'https://techcrunch.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Engadget',
        'url': 'https://www.engadget.com/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The Next Web',
        'url': 'https://thenextweb.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'ZDNet',
        'url': 'https://www.zdnet.com/news/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Mashable Tech',
        'url': 'https://mashable.com/feeds/rss/tech',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'SpaceNews',
        'url': 'https://spacenews.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The Verge AI',
        'url': 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Ars Technica AI',
        'url': 'https://arstechnica.com/ai/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'AI News',
        'url': 'https://www.artificialintelligence-news.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'SiliconAngle AI',
        'url': 'https://siliconangle.com/category/ai/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': "Tom's Guide",
        'url': 'https://www.tomsguide.com/feeds/all',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': "Tom's Hardware",
        'url': 'https://www.tomshardware.com/feeds/all',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': '9to5Mac',
        'url': 'https://9to5mac.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': '9to5Google',
        'url': 'https://9to5google.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'MacRumors',
        'url': 'https://feeds.macrumors.com/MacRumors-All',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Android Authority',
        'url': 'https://www.androidauthority.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'CNET',
        'url': 'https://www.cnet.com/rss/news/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Digital Trends',
        'url': 'https://www.digitaltrends.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'How-To Geek',
        'url': 'https://www.howtogeek.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Ars Technica',
        'url': 'https://arstechnica.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'TechRadar',
        'url': 'https://www.techradar.com/rss',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The Verge',
        'url': 'https://www.theverge.com/rss/index.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'TechCrunch',
        'url': 'https://techcrunch.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Wired',
        'url': 'https://www.wired.com/feed/rss',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Engadget',
        'url': 'https://www.engadget.com/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'AnandTech',
        'url': 'https://www.anandtech.com/rss/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The Information',
        'url': 'https://www.theinformation.com/feed',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'MIT Technology Review',
        'url': 'https://www.technologyreview.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'IEEE Spectrum',
        'url': 'https://spectrum.ieee.org/rss/fulltext',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'VentureBeat',
        'url': 'https://venturebeat.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The Register',
        'url': 'https://www.theregister.com/headlines.atom',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'ZDNet',
        'url': 'https://www.zdnet.com/news/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Mashable Tech',
        'url': 'https://mashable.com/feeds/rss/tech',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Gizmodo',
        'url': 'https://gizmodo.com/rss',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Slashdot',
        'url': 'https://rss.slashdot.org/Slashdot/slashdotMain',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'Hacker News (Front Page)',
        'url': 'https://hnrss.org/frontpage',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Stratechery',
        'url': 'https://stratechery.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Daring Fireball',
        'url': 'https://daringfireball.net/feeds/main',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'GitHub Blog',
        'url': 'https://github.blog/feed/',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'OpenAI Blog',
        'url': 'https://openai.com/blog/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Anthropic News',
        'url': 'https://www.anthropic.com/news/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Google DeepMind Blog',
        'url': 'https://deepmind.google/blog/rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Hugging Face Blog',
        'url': 'https://huggingface.co/blog/feed.xml',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'PCMag News',
        'url': 'https://www.pcmag.com/feeds/rss/latest',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'GSMArena',
        'url': 'https://www.gsmarena.com/rss-news-reviews.php3',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Phandroid',
        'url': 'https://phandroid.com/feed/',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'AppleInsider',
        'url': 'https://appleinsider.com/news.rss',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'XDA Developers',
        'url': 'https://www.xda-developers.com/feed/',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'NVIDIA Blog',
        'url': 'https://blogs.nvidia.com/feed/',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'Cloudflare Blog',
        'url': 'https://blog.cloudflare.com/rss/',
        'category': 'technology',
        'tier': 'standard',
    },
    {
        'name': 'Nature',
        'url': 'https://www.nature.com/nature.rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Science Magazine',
        'url': 'https://www.science.org/rss/news_current.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Science News',
        'url': 'https://www.sciencenews.org/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'New Scientist',
        'url': 'https://www.newscientist.com/feed/home',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Live Science',
        'url': 'https://www.livescience.com/feeds/all',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Popular Science',
        'url': 'https://www.popsci.com/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Quanta Magazine',
        'url': 'https://www.quantamagazine.org/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Science Daily',
        'url': 'https://www.sciencedaily.com/rss/all.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Scientific American Basic Science',
        'url': 'http://rss.sciam.com/basic-science',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Popular Mechanics',
        'url': 'https://www.popularmechanics.com/rss/all.xml/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Smithsonian Smart News',
        'url': 'https://www.smithsonianmag.com/rss/smart-news/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Futurism',
        'url': 'https://futurism.com/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'ScienceAlert',
        'url': 'https://www.sciencealert.com/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Ars Technica Science',
        'url': 'https://arstechnica.com/science/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Aeon',
        'url': 'https://aeon.co/feed.rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'New Atlas',
        'url': 'https://newatlas.com/index.rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Mental Floss',
        'url': 'https://www.mentalfloss.com/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Big Think',
        'url': 'https://bigthink.com/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'The Conversation',
        'url': 'https://theconversation.com/us/articles.atom',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'ZME Science',
        'url': 'https://www.zmescience.com/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'RealClearScience',
        'url': 'https://www.realclearscience.com/index.xml',
        'category': 'science',
        'tier': 'standard',
    },
    {
        'name': 'Knowable Magazine',
        'url': 'https://knowablemagazine.org/rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Nautilus',
        'url': 'https://nautil.us/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Quanta Magazine',
        'url': 'https://www.quantamagazine.org/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Eos',
        'url': 'https://eos.org/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'PNAS',
        'url': 'https://www.pnas.org/rss/current.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Cell Press',
        'url': 'https://www.cell.com/cell/inpress.rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'eLife',
        'url': 'https://elifesciences.org/rss/recent.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Earth.com',
        'url': 'https://www.earth.com/feed/',
        'category': 'science',
        'tier': 'standard',
    },
    {
        'name': 'SciTechDaily',
        'url': 'https://scitechdaily.com/feed/',
        'category': 'science',
        'tier': 'standard',
    },
    {
        'name': 'EurekAlert!',
        'url': 'https://www.eurekalert.org/rss/breaking_news.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Science News',
        'url': 'https://www.sciencenews.org/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Inverse Science',
        'url': 'https://www.inverse.com/rss/science',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'BBC Science Focus',
        'url': 'https://www.sciencefocus.com/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Cosmos Magazine',
        'url': 'https://cosmosmagazine.com/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Sci.News',
        'url': 'https://www.sci.news/feed',
        'category': 'science',
        'tier': 'standard',
    },
    {
        'name': 'NIH News',
        'url': 'https://www.nih.gov/news-releases/feed.xml',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'CDC Newsroom',
        'url': 'https://tools.cdc.gov/api/v2/resources/media/316422.rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'NOAA News',
        'url': 'https://www.noaa.gov/news/all/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'NASA Image of the Day',
        'url': 'https://www.nasa.gov/feeds/iotd-feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'JPL News',
        'url': 'https://www.jpl.nasa.gov/feeds/news/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'European Space Agency',
        'url': 'https://www.esa.int/rssfeed/Our_Activities/Space_News',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'MIT News',
        'url': 'https://news.mit.edu/rss/feed',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'MIT Research',
        'url': 'https://news.mit.edu/rss/research',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'MIT Artificial Intelligence',
        'url': 'https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'Harvard Gazette',
        'url': 'https://news.harvard.edu/gazette/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'NASA',
        'url': 'https://www.nasa.gov/rss/dyn/breaking_news.rss',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'ESA (European Space Agency)',
        'url': 'https://www.esa.int/rssfeed/Our_Activities/Space_News',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Astronomy Magazine',
        'url': 'https://www.astronomy.com/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Sky & Telescope',
        'url': 'https://skyandtelescope.org/astronomy-news/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Universe Today',
        'url': 'https://www.universetoday.com/feed',
        'category': 'space',
        'tier': 'premium',
    },
    {
        'name': 'Space.com',
        'url': 'https://www.space.com/feeds/all',
        'category': 'space',
        'tier': 'premium',
    },
    {
        'name': 'SpaceFlightNow',
        'url': 'https://spaceflightnow.com/feed/',
        'category': 'space',
        'tier': 'premium',
    },
    {
        'name': 'NASA Image of the Day',
        'url': 'https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss',
        'category': 'space',
        'tier': 'premium',
    },
    {
        'name': 'Phys.org Space',
        'url': 'https://phys.org/rss-feed/space-news/',
        'category': 'space',
        'tier': 'premium',
    },
    {
        'name': 'EarthSky',
        'url': 'https://earthsky.org/feed/',
        'category': 'space',
        'tier': 'premium',
    },
    {
        'name': 'Grist',
        'url': 'https://grist.org/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Climate Home News',
        'url': 'https://www.climatechangenews.com/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Carbon Brief',
        'url': 'https://www.carbonbrief.org/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Yale Climate Connections',
        'url': 'https://yaleclimateconnections.org/feed/',
        'category': 'science',
        'tier': 'premium',
    },
    {
        'name': 'Politico Congress',
        'url': 'https://rss.politico.com/congress.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Politico Healthcare',
        'url': 'https://rss.politico.com/healthcare.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Politico Defense',
        'url': 'https://rss.politico.com/defense.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Politico Economy',
        'url': 'https://rss.politico.com/economy.xml',
        'category': 'business',
        'tier': 'premium',
    },
    {
        'name': 'Politico Energy',
        'url': 'https://rss.politico.com/energy.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Politico Politics News',
        'url': 'https://rss.politico.com/politics-news.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'ABC News International',
        'url': 'https://abcnews.go.com/abcnews/internationalheadlines',
        'category': 'news',
        'tier': 'premium',
        'image_size': 'largest',
    },
    {
        'name': 'CBS News Main',
        'url': 'https://www.cbsnews.com/latest/rss/main',
        'category': 'news',
        'tier': 'premium',
        'fetch_image_from_website': True,
    },
    {
        'name': 'CBS News US',
        'url': 'https://www.cbsnews.com/latest/rss/us',
        'category': 'news',
        'tier': 'premium',
        'fetch_image_from_website': True,
    },
    {
        'name': 'CBS News World',
        'url': 'https://www.cbsnews.com/latest/rss/world',
        'category': 'news',
        'tier': 'premium',
        'fetch_image_from_website': True,
    },
    {
        'name': 'NBC News',
        'url': 'https://feeds.nbcnews.com/nbcnews/public/news',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Fox News Latest',
        'url': 'https://moxie.foxnews.com/google-publisher/latest.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Fox News World',
        'url': 'https://moxie.foxnews.com/google-publisher/world.xml',
        'category': 'news',
        'tier': 'premium',
    },
    {
        'name': 'Fox News Tech',
        'url': 'https://moxie.foxnews.com/google-publisher/tech.xml',
        'category': 'technology',
        'tier': 'premium',
    },
    {
        'name': 'The Guardian UK',
        'url': 'https://www.theguardian.com/uk/rss',
        'category': 'news',
        'tier': 'premium',
        'image_size': 'largest',
    },
    {
        'name': 'The Guardian World',
        'url': 'https://www.theguardian.com/world/rss',
        'category': 'news',
        'tier': 'premium',
        'image_size': 'largest',
    },
    {
        'name': 'The Hindu',
        'url': 'https://www.thehindu.com/news/feeder/default.rss',
        'category': 'news',
        'tier': 'premium',
        'country': 'India',
    },
    {
        'name': 'Hindustan Times',
        'url': 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'India',
    },
    {
        'name': 'NDTV',
        'url': 'https://feeds.feedburner.com/ndtvnews-top-stories',
        'category': 'news',
        'tier': 'premium',
        'country': 'India',
    },
    {
        'name': 'News18',
        'url': 'https://www.news18.com/commonfeeds/v1/eng/rss/india.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'India',
    },
    {
        'name': 'Daily Sabah',
        'url': 'https://www.dailysabah.com/rss/turkiye',
        'category': 'news',
        'tier': 'premium',
        'country': 'Turkiye',
    },
    {
        'name': 'Hürriyet',
        'url': 'https://www.hurriyet.com.tr/rss/anasayfa',
        'category': 'news',
        'tier': 'premium',
        'country': 'Turkiye',
    },
    {
        'name': 'Cumhuriyet',
        'url': 'https://www.cumhuriyet.com.tr/rss/turkiye',
        'category': 'news',
        'tier': 'premium',
        'country': 'Turkiye',
    },
    {
        'name': 'Sözcü',
        'url': 'https://www.sozcu.com.tr/feeds-rss-category-gundem',
        'category': 'news',
        'tier': 'premium',
        'country': 'Turkiye',
    },
    {
        'name': 'TRT World',
        'url': 'https://www.trtworld.com/feed/rss.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Turkiye',
    },
    {
        'name': 'Anadolu Agency English',
        'url': 'https://www.aa.com.tr/en/rss/default?cat=guncel',
        'category': 'news',
        'tier': 'premium',
        'country': 'Turkiye',
    },
    {
        'name': 'Global Times',
        'url': 'https://www.globaltimes.cn/rss/outbrain.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'China',
    },
    {
        'name': 'China Daily',
        'url': 'http://www.chinadaily.com.cn/rss/china_rss.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'China',
    },
    {
        'name': 'Sixth Tone',
        'url': 'https://www.sixthtone.com/rss',
        'category': 'news',
        'tier': 'premium',
        'country': 'China',
    },
    {
        'name': 'TASS',
        'url': 'https://tass.com/rss/v2.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Russia',
    },
    {
        'name': 'The Moscow Times',
        'url': 'https://www.themoscowtimes.com/rss/news',
        'category': 'news',
        'tier': 'premium',
        'country': 'Russia',
    },
    {
        'name': 'Meduza English',
        'url': 'https://meduza.io/rss/en/all',
        'category': 'news',
        'tier': 'premium',
        'country': 'Russia',
    },
    {
        'name': 'Russia in Global Affairs',
        'url': 'https://eng.globalaffairs.ru/feed',
        'category': 'news',
        'tier': 'premium',
        'country': 'Russia',
    },
    {
        'name': 'Ukrainska Pravda (English)',
        'url': 'https://www.pravda.com.ua/eng/rss/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Ukraine',
    },
    {
        'name': 'UNIAN',
        'url': 'https://rss.unian.net/site/news_eng.rss',
        'category': 'news',
        'tier': 'premium',
        'country': 'Ukraine',
    },
    {
        'name': 'The Kyiv Independent',
        'url': 'https://kyivindependent.com/feed/news/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Ukraine',
    },
    {
        'name': 'NV.ua English',
        'url': 'https://english.nv.ua/rss/all.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Ukraine',
    },
    {
        'name': 'Kyiv Post',
        'url': 'https://www.kyivpost.com/feed',
        'category': 'news',
        'tier': 'premium',
        'country': 'Ukraine',
    },
    {
        'name': 'Der Spiegel International',
        'url': 'https://www.spiegel.de/international/index.rss',
        'category': 'news',
        'tier': 'premium',
        'country': 'Germany',
    },
    {
        'name': 'Frankfurter Allgemeine',
        'url': 'https://www.faz.net/rss/aktuell/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Germany',
    },
    {
        'name': 'Süddeutsche Zeitung',
        'url': 'https://rss.sueddeutsche.de/rss/Topthemen',
        'category': 'news',
        'tier': 'premium',
        'country': 'Germany',
    },
    {
        'name': 'Die Welt',
        'url': 'https://www.welt.de/feeds/latest.rss',
        'category': 'news',
        'tier': 'premium',
        'country': 'Germany',
    },
    {
        'name': 'Le Monde',
        'url': 'https://www.lemonde.fr/rss/une.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'France',
    },
    {
        'name': 'Libération',
        'url': 'https://www.liberation.fr/arc/outboundfeeds/rss-all/',
        'category': 'news',
        'tier': 'premium',
        'country': 'France',
    },
    {
        'name': "L'Obs",
        'url': 'https://www.nouvelobs.com/rss.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'France',
    },
    {
        'name': 'La Vanguardia',
        'url': 'https://www.lavanguardia.com/rss/home.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Spain',
    },
    {
        'name': 'El Mundo',
        'url': 'https://www.elmundo.es/rss/portada.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Spain',
    },
    {
        'name': 'ABC España',
        'url': 'https://www.abc.es/rss/feeds/abc_EspanaEspana.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Spain',
    },
    {
        'name': 'ANSA',
        'url': 'https://www.ansa.it/sito/ansait_rss.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Italy',
    },
    {
        'name': 'Corriere della Sera',
        'url': 'https://www.corriere.it/rss/homepage.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Italy',
    },
    {
        'name': 'La Repubblica',
        'url': 'https://www.repubblica.it/rss/homepage/rss2.0.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Italy',
    },
    {
        'name': 'Asahi Shimbun',
        'url': 'https://rss.asahi.com/rss/asahi/newsheadlines.rdf',
        'category': 'news',
        'tier': 'premium',
        'country': 'Japan',
    },
    {
        'name': 'The Japan News (Yomiuri)',
        'url': 'https://japannews.yomiuri.co.jp/feed/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Japan',
    },
    {
        'name': 'Japan Today',
        'url': 'https://www.japantoday.com/feed',
        'category': 'news',
        'tier': 'premium',
        'country': 'Japan',
    },
    {
        'name': 'nippon.com',
        'url': 'https://www.nippon.com/en/feed/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Japan',
    },
    {
        'name': 'NHK News',
        'url': 'https://www3.nhk.or.jp/rss/news/cat0.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Japan',
    },
    {
        'name': 'ABC News Australia',
        'url': 'https://www.abc.net.au/news/feed/2942460/rss.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Australia',
    },
    {
        'name': '9News Australia',
        'url': 'https://www.9news.com.au/rss',
        'category': 'news',
        'tier': 'premium',
        'country': 'Australia',
    },
    {
        'name': 'The Age',
        'url': 'https://www.theage.com.au/rss/feed.xml',
        'category': 'news',
        'tier': 'premium',
        'country': 'Australia',
    },
    {
        'name': 'News.com.au',
        'url': 'https://www.news.com.au/content-feeds/latest-news-national/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Australia',
    },
    {
        'name': 'Global News',
        'url': 'https://globalnews.ca/feed/',
        'category': 'news',
        'tier': 'premium',
        'country': 'Canada',
    },
    {
        'name': 'National Post',
        'url': 'https://nationalpost.com/feed',
        'category': 'news',
        'tier': 'premium',
        'country': 'Canada',
    },
    {
        'name': 'ESPN Top Headlines',
        'url': 'https://www.espn.com/espn/rss/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN Soccer',
        'url': 'https://www.espn.com/espn/rss/soccer/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN NBA',
        'url': 'https://www.espn.com/espn/rss/nba/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN NFL',
        'url': 'https://www.espn.com/espn/rss/nfl/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN Tennis',
        'url': 'https://www.espn.com/espn/rss/tennis/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN MMA',
        'url': 'https://www.espn.com/espn/rss/mma/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN Boxing',
        'url': 'https://www.espn.com/espn/rss/boxing/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN Golf',
        'url': 'https://www.espn.com/espn/rss/golf/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN NHL',
        'url': 'https://www.espn.com/espn/rss/nhl/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN MLB',
        'url': 'https://www.espn.com/espn/rss/mlb/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN Olympics',
        'url': 'https://www.espn.com/espn/rss/oly/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPN Horse Racing',
        'url': 'https://www.espn.com/espn/rss/horse/news',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport',
        'url': 'https://feeds.bbci.co.uk/sport/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport Football',
        'url': 'https://feeds.bbci.co.uk/sport/football/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport F1',
        'url': 'https://feeds.bbci.co.uk/sport/formula1/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport Tennis',
        'url': 'https://feeds.bbci.co.uk/sport/tennis/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport American Football',
        'url': 'https://feeds.bbci.co.uk/sport/american-football/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport Rugby Union',
        'url': 'https://feeds.bbci.co.uk/sport/rugby-union/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport Rugby League',
        'url': 'https://feeds.bbci.co.uk/sport/rugby-league/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport Athletics',
        'url': 'https://feeds.bbci.co.uk/sport/athletics/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'BBC Sport Golf',
        'url': 'https://feeds.bbci.co.uk/sport/golf/rss.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'F1 Official',
        'url': 'https://www.formula1.com/content/fom-website/en/latest/all.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'Motorsport.com F1',
        'url': 'https://www.motorsport.com/rss/f1/news/',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'CBS Sports NBA',
        'url': 'https://www.cbssports.com/rss/headlines/nba/',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'ESPNcricinfo',
        'url': 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'Yahoo Sports',
        'url': 'https://sports.yahoo.com/rss/',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'Sky Sports News',
        'url': 'https://www.skysports.com/rss/12040',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'FourFourTwo',
        'url': 'https://www.fourfourtwo.com/feeds/all',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'CBS Sports',
        'url': 'https://www.cbssports.com/rss/headlines/',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'Talksport',
        'url': 'https://talksport.com/feed/',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'Wrestling Inc',
        'url': 'https://www.wrestlinginc.com/feed/',
        'category': 'sports',
        'tier': 'standard',
    },
    {
        'name': 'ClutchPoints',
        'url': 'https://clutchpoints.com/feed/',
        'category': 'sports',
        'tier': 'premium',
    },
    {
        'name': 'CoinDesk',
        'url': 'https://www.coindesk.com/arc/outboundfeeds/rss/',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'CoinTelegraph',
        'url': 'https://cointelegraph.com/rss',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'The Block',
        'url': 'https://www.theblock.co/rss.xml',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'Decrypt',
        'url': 'https://decrypt.co/feed',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'Bitcoin Magazine',
        'url': 'https://bitcoinmagazine.com/.rss/full/',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'DL News',
        'url': 'https://www.dlnews.com/arc/outboundfeeds/rss/',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'The Defiant',
        'url': 'https://thedefiant.io/feed',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'Crypto Briefing',
        'url': 'https://cryptobriefing.com/feed/',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'CryptoSlate',
        'url': 'https://cryptoslate.com/feed/',
        'category': 'crypto',
        'tier': 'premium',
    },
    {
        'name': 'Self Magazine',
        'url': 'https://www.self.com/feed/rss',
        'category': 'health',
        'tier': 'premium',
    },
    {
        'name': 'Healthline',
        'url': 'https://www.healthline.com/rss/health-news',
        'category': 'health',
        'tier': 'premium',
    },
    {
        'name': "Runner's World",
        'url': 'https://www.runnersworld.com/rss/all.xml/',
        'category': 'health',
        'tier': 'premium',
    },
    {
        'name': "Men's Health",
        'url': 'https://www.menshealth.com/rss/all.xml/',
        'category': 'health',
        'tier': 'premium',
    },
    {
        'name': "Women's Health",
        'url': 'https://www.womenshealthmag.com/rss/all.xml/',
        'category': 'health',
        'tier': 'premium',
    },
]

# SPECIAL IMAGE HANDLING NOTES:
# - ABC News: Use largest image size (width=1600, height=900) - marked with image_size='largest'
# - CBS News: Fetch images from website via BrightData - marked with fetch_image_from_website=True
# - The Guardian: Use largest image size (width=700) - marked with image_size='largest'
#
# NON-ENGLISH FEEDS NOTE:
# - Some feeds (Turkiye, Russia, Germany, France, Spain, Italy, Japan) may return
#   articles in local languages. Gemini and Claude handle multilingual content natively -
#   they will read in any language and produce English output as instructed by the prompts.

# Legacy compatibility - convert RSS_FEEDS to ALL_SOURCES tuple format (name, url, country)
ALL_SOURCES = [(feed['name'], feed['url'], feed.get('country', '')) for feed in RSS_FEEDS]

# Only print stats when run directly (not when imported)
if __name__ == "__main__":
    print(f"Total RSS Feeds: {len(RSS_FEEDS)}")

    print(f"\nBreakdown by category:")
    categories = {}
    for feed in RSS_FEEDS:
        cat = feed['category']
        categories[cat] = categories.get(cat, 0) + 1

    for category in sorted(categories.keys()):
        count = categories[category]
        pct = count / len(RSS_FEEDS) * 100
        print(f"  {category.capitalize():15s}: {count:3d} feeds ({pct:5.1f}%)")

    print(f"\nCountry-tagged feeds:")
    countries = {}
    for feed in RSS_FEEDS:
        country = feed.get('country', 'Global/Untagged')
        countries[country] = countries.get(country, 0) + 1

    for country in sorted(countries.keys()):
        count = countries[country]
        print(f"  {country:25s}: {count:3d} feeds")

    # Check for duplicate names
    names = [feed['name'] for feed in RSS_FEEDS]
    duplicates = [name for name in set(names) if names.count(name) > 1]
    if duplicates:
        print(f"\nWARNING - Duplicate feed names: {duplicates}")
    else:
        print(f"\nNo duplicate feed names found.")
